package com.next2me.next2cash.controller;

import com.next2me.next2cash.BaseIntegrationTest;
import com.next2me.next2cash.model.CompanyEntity;
import com.next2me.next2cash.model.Project;
import com.next2me.next2cash.model.User;
import com.next2me.next2cash.repository.ProjectRepository;
import com.next2me.next2cash.support.TestDataBuilder;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;

import java.math.BigDecimal;
import java.util.Map;
import java.util.UUID;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * S80: validates that ProjectController rejects invalid status values with
 * HTTP 400 + clear error message, BEFORE attempting a DB save.
 *
 * <p>Before S80, sending an invalid status produced HTTP 403 with empty body
 * (DB CHECK constraint violation bubbling up through Spring's default error
 * pipeline). The new behavior is HTTP 400 with a human-readable error.
 *
 * <p>Note: H2 test schema is generated by Hibernate from JPA entities
 * (ddl-auto=create-drop), so the production CHECK constraint is NOT
 * present in the test DB. That is exactly why we validate at the
 * controller layer - to catch the problem early regardless of whether
 * the DB enforces it.
 */
class ProjectStatusValidationTest extends BaseIntegrationTest {

    @Autowired private TestDataBuilder tdb;
    @Autowired private ProjectRepository projectRepository;

    // ─── createProject ─────────────────────────────────────────────────

    @Test
    void createProject_withInvalidStatus_returns400() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80A", "Test Entity 80A");
        tdb.assignEntities(admin, ent);

        String body = objectMapper.writeValueAsString(Map.of(
            "name", "S80-Invalid-Status-Project",
            "ownerEntityId", ent.getId().toString(),
            "status", "FOOBAR"
        ));

        mockMvc.perform(post("/api/projects")
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.error").exists());
    }

    @Test
    void createProject_withValidStatus_returns201() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80B", "Test Entity 80B");
        tdb.assignEntities(admin, ent);

        String body = objectMapper.writeValueAsString(Map.of(
            "name", "S80-Valid-Status-Project",
            "ownerEntityId", ent.getId().toString(),
            "status", "IN_DEVELOPMENT"
        ));

        mockMvc.perform(post("/api/projects")
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.status").value("IN_DEVELOPMENT"));
    }

    @Test
    void createProject_withLowercaseStatus_isNormalizedAndAccepted() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80C", "Test Entity 80C");
        tdb.assignEntities(admin, ent);

        String body = objectMapper.writeValueAsString(Map.of(
            "name", "S80-Lowercase-Status",
            "ownerEntityId", ent.getId().toString(),
            "status", "live"
        ));

        mockMvc.perform(post("/api/projects")
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isCreated())
            .andExpect(jsonPath("$.data.status").value("LIVE"));
    }

    // ─── updateProject ─────────────────────────────────────────────────

    @Test
    void updateProject_withInvalidStatus_returns400() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80D", "Test Entity 80D");
        tdb.assignEntities(admin, ent);

        // Seed a project directly via repository (bypass controller).
        Project p = new Project();
        p.setName("S80-Update-Target");
        p.setOwnerEntityId(ent.getId());
        p.setStatus("PLANNING");
        p.setTotalBudget(BigDecimal.ZERO);
        p.setExpectedMonthlyRevenue(BigDecimal.ZERO);
        Project saved = projectRepository.save(p);

        String body = objectMapper.writeValueAsString(Map.of("status", "COMPLETED"));

        mockMvc.perform(put("/api/projects/" + saved.getId())
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isBadRequest())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.error").exists());
    }

    @Test
    void updateProject_withValidStatusTransition_returns200() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80E", "Test Entity 80E");
        tdb.assignEntities(admin, ent);

        Project p = new Project();
        p.setName("S80-Valid-Update-Target");
        p.setOwnerEntityId(ent.getId());
        p.setStatus("PLANNING");
        p.setTotalBudget(BigDecimal.ZERO);
        p.setExpectedMonthlyRevenue(BigDecimal.ZERO);
        Project saved = projectRepository.save(p);

        String body = objectMapper.writeValueAsString(Map.of("status", "TESTING"));

        mockMvc.perform(put("/api/projects/" + saved.getId())
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.status").value("TESTING"));
    }

    // ─── Misc edge cases ───────────────────────────────────────────────

    @Test
    void updateProject_withNullStatus_isIgnored() throws Exception {
        User admin = tdb.createAdmin("apostolos");
        String bearer = tdb.bearerToken(admin);
        CompanyEntity ent = tdb.createEntity("TESTENT80F", "Test Entity 80F");
        tdb.assignEntities(admin, ent);

        Project p = new Project();
        p.setName("S80-Null-Status-Update");
        p.setOwnerEntityId(ent.getId());
        p.setStatus("PAUSED");
        p.setTotalBudget(BigDecimal.ZERO);
        p.setExpectedMonthlyRevenue(BigDecimal.ZERO);
        Project saved = projectRepository.save(p);

        // Body without "status" key at all -> existing status preserved
        String body = objectMapper.writeValueAsString(Map.of("description", "updated desc only"));

        mockMvc.perform(put("/api/projects/" + saved.getId())
                .header("Authorization", bearer)
                .contentType(MediaType.APPLICATION_JSON)
                .content(body))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.data.status").value("PAUSED"));
    }
}
